[package]
name = "stan-language-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "stan-language-server"
path = "src/main.rs"

[dependencies]
stan-language = { path = "../stan-language" }
tokio.workspace = true
tower-lsp-server.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
serde_json.workspace = true
