// @generated by `cargo run -p xtask -- refresh-stan`; do not edit by hand.

#[rustfmt::skip]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Token)]
pub enum Distribution {
    #[token("bernoulli")]
    Bernoulli,
    #[token("bernoulli_logit")]
    BernoulliLogit,
    #[token("bernoulli_logit_glm")]
    BernoulliLogitGlm,
    #[token("beta")]
    Beta,
    #[token("beta_binomial")]
    BetaBinomial,
    #[token("beta_neg_binomial")]
    BetaNegBinomial,
    #[token("beta_proportion")]
    BetaProportion,
    #[token("binomial")]
    Binomial,
    #[token("binomial_logit")]
    BinomialLogit,
    #[token("binomial_logit_glm")]
    BinomialLogitGlm,
    #[token("categorical")]
    Categorical,
    #[token("categorical_logit")]
    CategoricalLogit,
    #[token("categorical_logit_glm")]
    CategoricalLogitGlm,
    #[token("cauchy")]
    Cauchy,
    #[token("chi_square")]
    ChiSquare,
    #[token("dirichlet")]
    Dirichlet,
    #[token("dirichlet_multinomial")]
    DirichletMultinomial,
    #[token("discrete_range")]
    DiscreteRange,
    #[token("double_exponential")]
    DoubleExponential,
    #[token("exp_mod_normal")]
    ExpModNormal,
    #[token("exponential")]
    Exponential,
    #[token("frechet")]
    Frechet,
    #[token("gamma")]
    Gamma,
    #[token("gaussian_dlm_obs")]
    GaussianDlmObs,
    #[token("gumbel")]
    Gumbel,
    #[token("hypergeometric")]
    Hypergeometric,
    #[token("inv_chi_square")]
    InvChiSquare,
    #[token("inv_gamma")]
    InvGamma,
    #[token("inv_wishart")]
    InvWishart,
    #[token("inv_wishart_cholesky")]
    InvWishartCholesky,
    #[token("laplace_marginal_bernoulli_logit")]
    LaplaceMarginalBernoulliLogit,
    #[token("laplace_marginal_neg_binomial_2_log")]
    LaplaceMarginalNegBinomial2Log,
    #[token("laplace_marginal_poisson_log")]
    LaplaceMarginalPoissonLog,
    #[token("laplace_marginal_tol_bernoulli_logit")]
    LaplaceMarginalTolBernoulliLogit,
    #[token("laplace_marginal_tol_neg_binomial_2_log")]
    LaplaceMarginalTolNegBinomial2Log,
    #[token("laplace_marginal_tol_poisson_log")]
    LaplaceMarginalTolPoissonLog,
    #[token("lkj_corr")]
    LkjCorr,
    #[token("lkj_corr_cholesky")]
    LkjCorrCholesky,
    #[token("lkj_cov")]
    LkjCov,
    #[token("logistic")]
    Logistic,
    #[token("loglogistic")]
    Loglogistic,
    #[token("lognormal")]
    Lognormal,
    #[token("multi_gp")]
    MultiGp,
    #[token("multi_gp_cholesky")]
    MultiGpCholesky,
    #[token("multi_normal")]
    MultiNormal,
    #[token("multi_normal_cholesky")]
    MultiNormalCholesky,
    #[token("multi_normal_prec")]
    MultiNormalPrec,
    #[token("multi_student_t")]
    MultiStudentT,
    #[token("multi_student_t_cholesky")]
    MultiStudentTCholesky,
    #[token("multinomial")]
    Multinomial,
    #[token("multinomial_logit")]
    MultinomialLogit,
    #[token("neg_binomial")]
    NegBinomial,
    #[token("neg_binomial_2")]
    NegBinomial2,
    #[token("neg_binomial_2_log")]
    NegBinomial2Log,
    #[token("neg_binomial_2_log_glm")]
    NegBinomial2LogGlm,
    #[token("normal")]
    Normal,
    #[token("normal_id_glm")]
    NormalIdGlm,
    #[token("ordered_logistic")]
    OrderedLogistic,
    #[token("ordered_logistic_glm")]
    OrderedLogisticGlm,
    #[token("ordered_probit")]
    OrderedProbit,
    #[token("pareto")]
    Pareto,
    #[token("pareto_type_2")]
    ParetoType2,
    #[token("poisson")]
    Poisson,
    #[token("poisson_log")]
    PoissonLog,
    #[token("poisson_log_glm")]
    PoissonLogGlm,
    #[token("rayleigh")]
    Rayleigh,
    #[token("scaled_inv_chi_square")]
    ScaledInvChiSquare,
    #[token("skew_double_exponential")]
    SkewDoubleExponential,
    #[token("skew_normal")]
    SkewNormal,
    #[token("std_normal")]
    StdNormal,
    #[token("student_t")]
    StudentT,
    #[token("uniform")]
    Uniform,
    #[token("von_mises")]
    VonMises,
    #[token("weibull")]
    Weibull,
    #[token("wiener")]
    Wiener,
    #[token("wishart")]
    Wishart,
    #[token("wishart_cholesky")]
    WishartCholesky,
    #[token("yule_simon")]
    YuleSimon,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DistributionKind {
    Discrete,
    Continuous,
}

#[rustfmt::skip]
impl Distribution {
    pub const fn kind(&self) -> DistributionKind {
        match self {
            Self::Bernoulli => DistributionKind::Discrete,
            Self::BernoulliLogit => DistributionKind::Discrete,
            Self::BernoulliLogitGlm => DistributionKind::Discrete,
            Self::Beta => DistributionKind::Continuous,
            Self::BetaBinomial => DistributionKind::Discrete,
            Self::BetaNegBinomial => DistributionKind::Discrete,
            Self::BetaProportion => DistributionKind::Continuous,
            Self::Binomial => DistributionKind::Discrete,
            Self::BinomialLogit => DistributionKind::Discrete,
            Self::BinomialLogitGlm => DistributionKind::Discrete,
            Self::Categorical => DistributionKind::Discrete,
            Self::CategoricalLogit => DistributionKind::Discrete,
            Self::CategoricalLogitGlm => DistributionKind::Discrete,
            Self::Cauchy => DistributionKind::Continuous,
            Self::ChiSquare => DistributionKind::Continuous,
            Self::Dirichlet => DistributionKind::Continuous,
            Self::DirichletMultinomial => DistributionKind::Discrete,
            Self::DiscreteRange => DistributionKind::Discrete,
            Self::DoubleExponential => DistributionKind::Continuous,
            Self::ExpModNormal => DistributionKind::Continuous,
            Self::Exponential => DistributionKind::Continuous,
            Self::Frechet => DistributionKind::Continuous,
            Self::Gamma => DistributionKind::Continuous,
            Self::GaussianDlmObs => DistributionKind::Continuous,
            Self::Gumbel => DistributionKind::Continuous,
            Self::Hypergeometric => DistributionKind::Discrete,
            Self::InvChiSquare => DistributionKind::Continuous,
            Self::InvGamma => DistributionKind::Continuous,
            Self::InvWishart => DistributionKind::Continuous,
            Self::InvWishartCholesky => DistributionKind::Continuous,
            Self::LaplaceMarginalBernoulliLogit => DistributionKind::Discrete,
            Self::LaplaceMarginalNegBinomial2Log => DistributionKind::Discrete,
            Self::LaplaceMarginalPoissonLog => DistributionKind::Discrete,
            Self::LaplaceMarginalTolBernoulliLogit => DistributionKind::Discrete,
            Self::LaplaceMarginalTolNegBinomial2Log => DistributionKind::Discrete,
            Self::LaplaceMarginalTolPoissonLog => DistributionKind::Discrete,
            Self::LkjCorr => DistributionKind::Continuous,
            Self::LkjCorrCholesky => DistributionKind::Continuous,
            Self::LkjCov => DistributionKind::Continuous,
            Self::Logistic => DistributionKind::Continuous,
            Self::Loglogistic => DistributionKind::Continuous,
            Self::Lognormal => DistributionKind::Continuous,
            Self::MultiGp => DistributionKind::Continuous,
            Self::MultiGpCholesky => DistributionKind::Continuous,
            Self::MultiNormal => DistributionKind::Continuous,
            Self::MultiNormalCholesky => DistributionKind::Continuous,
            Self::MultiNormalPrec => DistributionKind::Continuous,
            Self::MultiStudentT => DistributionKind::Continuous,
            Self::MultiStudentTCholesky => DistributionKind::Continuous,
            Self::Multinomial => DistributionKind::Discrete,
            Self::MultinomialLogit => DistributionKind::Discrete,
            Self::NegBinomial => DistributionKind::Discrete,
            Self::NegBinomial2 => DistributionKind::Discrete,
            Self::NegBinomial2Log => DistributionKind::Discrete,
            Self::NegBinomial2LogGlm => DistributionKind::Discrete,
            Self::Normal => DistributionKind::Continuous,
            Self::NormalIdGlm => DistributionKind::Continuous,
            Self::OrderedLogistic => DistributionKind::Discrete,
            Self::OrderedLogisticGlm => DistributionKind::Discrete,
            Self::OrderedProbit => DistributionKind::Discrete,
            Self::Pareto => DistributionKind::Continuous,
            Self::ParetoType2 => DistributionKind::Continuous,
            Self::Poisson => DistributionKind::Discrete,
            Self::PoissonLog => DistributionKind::Discrete,
            Self::PoissonLogGlm => DistributionKind::Discrete,
            Self::Rayleigh => DistributionKind::Continuous,
            Self::ScaledInvChiSquare => DistributionKind::Continuous,
            Self::SkewDoubleExponential => DistributionKind::Continuous,
            Self::SkewNormal => DistributionKind::Continuous,
            Self::StdNormal => DistributionKind::Continuous,
            Self::StudentT => DistributionKind::Continuous,
            Self::Uniform => DistributionKind::Continuous,
            Self::VonMises => DistributionKind::Continuous,
            Self::Weibull => DistributionKind::Continuous,
            Self::Wiener => DistributionKind::Continuous,
            Self::Wishart => DistributionKind::Continuous,
            Self::WishartCholesky => DistributionKind::Continuous,
            Self::YuleSimon => DistributionKind::Discrete,
        }
    }
}
